name: Benchmark Push

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 'main'

jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - name: Setup Actions User
          run: |
                git config user.name github-actions[bot]
                git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        - uses: actions-rust-lang/setup-rust-toolchain@v1
        - name: Build and run benchmarks
          run: cargo bench
        # Push To benchmarks-result branch
        - name: Push benchmark results
          run: |
            git add --force target/criterion
            git commit -m "Update Benchmark Results"
            git reset --hard main
            git push --force